#!/bin/bash

# prepare_instance.sh — untimed setup before each instance.
#   args: v1 <benchmark> <instance> <params>
#
# Makes sure the warm CORA.cpp daemon is up (see src/server.cpp), so that the thread pool
# and the first allocations of a fresh process never land in a measurement. A daemon that
# does not answer — dead, or still busy with an instance the harness timed out — is
# replaced. The instance's inputs are generated by run_instance.sh.
#
# Always exits 0: without a daemon, run_instance.sh runs the instance directly.

set -u

VERSION_STRING="v1"
if [ "$1" != "$VERSION_STRING" ]; then
    echo "Expected first argument (version string) '$VERSION_STRING', got '$1'"
    exit 1
fi

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/coracpp_lib.sh"
START_TIMEOUT="${CORACPP_START_TIMEOUT:-120}"

mkdir -p "$SRV_DIR"

if ask ping 5 && [ "$REPLY" = pong ]; then
    echo "[prepare] CORA.cpp daemon is up"
    exit 0
fi

PID="$(cat "$SRV_DIR/server.pid" 2>/dev/null)"
rm -f "$SRV_DIR/server.pid"
# The pid may have been reused since, so only a process that still is the daemon is killed.
if [ -n "$PID" ] && grep -qa "coracpp" "/proc/$PID/cmdline" 2>/dev/null; then
    echo "[prepare] replacing the unresponsive CORA.cpp daemon"
    kill -KILL "$PID"
    # The port frees once the process is gone.
    for _ in $(seq 50); do ask ping 1; [ $? -eq 1 ] && break; sleep 0.1; done
fi

echo "[prepare] starting the CORA.cpp daemon"
# Own session, so the harness's process-group kill of a timed-out run leaves it alone, and
# no inherited stdout, which the harness waits on.
( exec setsid "$CORACPP" serve "$SRV_DIR" ) > "$SRV_DIR/server.log" 2>&1 < /dev/null &

SECONDS=0
while [ "$SECONDS" -lt "$START_TIMEOUT" ]; do
    if ask ping 5 && [ "$REPLY" = pong ]; then
        echo "[prepare] CORA.cpp daemon is up after ${SECONDS}s"
        exit 0
    fi
    kill -0 $! 2>/dev/null || break
    sleep 0.2
done

echo "[prepare] the CORA.cpp daemon did not come up; run_instance.sh will run directly"
cat "$SRV_DIR/server.log"
exit 0
